spring.application.name=money_management_system

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/money_management_system
spring.datasource.username=postgres
spring.datasource.password=Ruhul@2002

# Server Configuration
server.servlet.context-path=/api/v1.0


#JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format.sql = true


## SQL Initialization
#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql